{
 "title": "System Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Global Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "rate(CamelExchangesTotal_total[$__rate_interval])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Failed Exchanges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "CamelExchangesFailed_total", "legendFormat": "{{routeId}}" }
   ]
  },
  {
   "title": "Route Policy Seconds Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "CamelRoutePolicy_seconds_max", "legendFormat": "{{routeId}}" }
   ]
  },
  {
   "title": "Checkout time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "CamelRoutePolicy_seconds_max{routeId=\"repositories-clone\"}",
     "legendFormat": "{{routeId}}"
    },
    {
     "expr": "CamelRoutePolicy_seconds_max{routeId=\"repositories-pull\"}",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Commit Service Routes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "CamelRoutesRunning_routes", "legendFormat": "__auto" }
   ]
  }
 ]
}